//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAC_Entidades_10
{
    using System;
    using System.Collections.Generic;
    
    public partial class CITAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CITAS()
        {
            this.CONSULTAS = new HashSet<CONSULTAS>();
        }
    
        public int Id_cita { get; set; }
        public int Id_paciente { get; set; }
        public Nullable<int> Id_hospital { get; set; }
        public int Id_medico { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<System.DateTime> Hora { get; set; }
        public Nullable<int> Estado { get; set; }
        public string Observacion { get; set; }
    
        public virtual CITA_ESTADOS CITA_ESTADOS { get; set; }
        public virtual HOSPITALES HOSPITALES { get; set; }
        public virtual MEDICOS MEDICOS { get; set; }
        public virtual PACIENTES PACIENTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONSULTAS> CONSULTAS { get; set; }
    }
}
