//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAC_Entidades_10
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSULTAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONSULTAS()
        {
            this.EXAMENES = new HashSet<EXAMENES>();
            this.RECETA = new HashSet<RECETA>();
        }
    
        public int Id_consulta { get; set; }
        public Nullable<int> Id_cita { get; set; }
        public Nullable<decimal> Talla { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public string Presion { get; set; }
        public string Sintomas { get; set; }
        public string Diagnostico { get; set; }
    
        public virtual CITAS CITAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXAMENES> EXAMENES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECETA> RECETA { get; set; }
    }
}
