//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAC_Entidades_10
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXAMENES
    {
        public int Id_orden { get; set; }
        public Nullable<int> Id_Consulta { get; set; }
        public Nullable<int> Id_examen { get; set; }
        public string Detalle { get; set; }
    
        public virtual CONSULTAS CONSULTAS { get; set; }
        public virtual TIPO_EXAMENES TIPO_EXAMENES { get; set; }
    }
}
