//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAC_Entidades_10
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOSPITALES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOSPITALES()
        {
            this.CITAS = new HashSet<CITAS>();
            this.MEDICOS = new HashSet<MEDICOS>();
        }
    
        public int Id_hospital { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Tipo { get; set; }
        public Nullable<int> Categoria { get; set; }
        public Nullable<int> Area { get; set; }
        public Nullable<int> Provincia { get; set; }
        public Nullable<int> Canton { get; set; }
        public Nullable<int> Parroquia { get; set; }
        public string Direccion { get; set; }
        public Nullable<System.DateTime> Fecha_Creacion { get; set; }
        public string Gerente { get; set; }
        public string Observacion { get; set; }
    
        public virtual AREAS AREAS { get; set; }
        public virtual CANTONES CANTONES { get; set; }
        public virtual CATEGORIAS CATEGORIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CITAS> CITAS { get; set; }
        public virtual PARROQUIAS PARROQUIAS { get; set; }
        public virtual PROVINCIAS PROVINCIAS { get; set; }
        public virtual TIPOS_H TIPOS_H { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEDICOS> MEDICOS { get; set; }
    }
}
