//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAC_Entidades_10
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEDICOS()
        {
            this.CITAS = new HashSet<CITAS>();
            this.MEDICO_ESPECIALIDAD = new HashSet<MEDICO_ESPECIALIDAD>();
        }
    
        public int Id_medico { get; set; }
        public string Cedula { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public Nullable<int> Id_hospital { get; set; }
        public Nullable<int> Cargo { get; set; }
        public Nullable<System.DateTime> FechaN { get; set; }
        public Nullable<int> Sexo { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Observacion { get; set; }
    
        public virtual CARGOS CARGOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CITAS> CITAS { get; set; }
        public virtual HOSPITALES HOSPITALES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEDICO_ESPECIALIDAD> MEDICO_ESPECIALIDAD { get; set; }
        public virtual SEXO SEXO1 { get; set; }
    }
}
