//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAC_Entidades_10
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACIENTES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PACIENTES()
        {
            this.CITAS = new HashSet<CITAS>();
        }
    
        public int Id_paciente { get; set; }
        public string Cedula { get; set; }
        public string Nombre1 { get; set; }
        public string Nombre2 { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
        public Nullable<int> TipoSangre { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<int> Sexo { get; set; }
        public Nullable<int> Condicion { get; set; }
        public string Direccion { get; set; }
        public string TelefonoP { get; set; }
        public string Email { get; set; }
        public string FamliarContacto { get; set; }
        public string TelefonoC { get; set; }
        public Nullable<int> Parentesco { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CITAS> CITAS { get; set; }
        public virtual CONDICIONES CONDICIONES { get; set; }
        public virtual PARENTESCOS PARENTESCOS { get; set; }
        public virtual SEXO SEXO1 { get; set; }
        public virtual TIPOS_SANGE TIPOS_SANGE { get; set; }
    }
}
