//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAC_Entidades_10
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECETA
    {
        public int Id_receta { get; set; }
        public Nullable<int> Id_consulta { get; set; }
        public string Medicinas { get; set; }
        public string Indicaciones { get; set; }
    
        public virtual CONSULTAS CONSULTAS { get; set; }
    }
}
