//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAC_Acceso_Datos_10
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using GAC_Entidades_10;
    
    public partial class GestionHospitalariaEntities : DbContext
    {
        public GestionHospitalariaEntities()
            : base("name=GestionHospitalariaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AREAS> AREAS { get; set; }
        public virtual DbSet<CANTONES> CANTONES { get; set; }
        public virtual DbSet<CARGOS> CARGOS { get; set; }
        public virtual DbSet<CATEGORIAS> CATEGORIAS { get; set; }
        public virtual DbSet<CITA_ESTADOS> CITA_ESTADOS { get; set; }
        public virtual DbSet<CITAS> CITAS { get; set; }
        public virtual DbSet<CONDICIONES> CONDICIONES { get; set; }
        public virtual DbSet<CONSULTAS> CONSULTAS { get; set; }
        public virtual DbSet<ESPECIALIDADES> ESPECIALIDADES { get; set; }
        public virtual DbSet<EXAMENES> EXAMENES { get; set; }
        public virtual DbSet<HOSPITALES> HOSPITALES { get; set; }
        public virtual DbSet<MEDICO_ESPECIALIDAD> MEDICO_ESPECIALIDAD { get; set; }
        public virtual DbSet<MEDICOS> MEDICOS { get; set; }
        public virtual DbSet<PACIENTES> PACIENTES { get; set; }
        public virtual DbSet<PARENTESCOS> PARENTESCOS { get; set; }
        public virtual DbSet<PARROQUIAS> PARROQUIAS { get; set; }
        public virtual DbSet<PROVINCIAS> PROVINCIAS { get; set; }
        public virtual DbSet<RECETA> RECETA { get; set; }
        public virtual DbSet<REGIONES> REGIONES { get; set; }
        public virtual DbSet<SEXO> SEXO { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TIPO_EXAMENES> TIPO_EXAMENES { get; set; }
        public virtual DbSet<TIPOS_H> TIPOS_H { get; set; }
        public virtual DbSet<TIPOS_SANGE> TIPOS_SANGE { get; set; }
    }
}
